name: Java CI with Maven

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        ports:
          - 15432:5432
        env:
          POSTGRES_DB: atmdb
          POSTGRES_USER: atmuser
          POSTGRES_PASSWORD: atmpassword
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify
